# Enable GitHub's "Sponsor" button by uncommenting and filling in any that apply.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [H-XX-D]
# ko_fi: your-handle
# open_collective: your-project
# custom: ["https://example.com/donate"]
